site_name: Dreamland Faces
copyright : "2023"
theme: 
      name: material
      font:
            text: Josefin Slab
      icon:
            :musical_score:
      palette:
            primary: white
            accent: green
      
      features:
            - navigation.instant
            - content.tooltips
            - navigation.tabs
            - navigation.tabs.sticky
            - navigation.top
      logo: images/logo2.png
      icon:
            repo: fontawesome/brands/github

plugins:
      - privacy
      - mkdocs-video
      
extra:
      generator: false

extra_css:
      - stylesheets/extra.css

markdown_extensions:
      - abbr
      - tables
      - attr_list
      - md_in_html
      - pymdownx.emoji:
            emoji_index: !!python/name:materialx.emoji.twemoji
            emoji_generator: !!python/name:materialx.emoji.to_svg
      - def_list
      - pymdownx.tasklist:
            custom_checkbox: true
      - pymdownx.snippets:
      - admonition
      - pymdownx.details
      - pymdownx.superfences
      - pymdownx.tabbed:
            alternate_style: true 
nav:
- About: 'index.md'
- Music: 'music.md'
- Video: 'video.md'
- Silent films: 'silentFilms.md'
- Upcoming Performances: 'upcomingPerformances.md'


